version: '3'
services:
  nginx:
    build: ./nginx
    env_file:
      - ./config.env
    volumes:
      - ./nginx_ssl:/etc/nginx/ssl
      - ./certbot_certs:/etc/letsencrypt
      - ./certbot_www:/var/www/certbot/${DOMAIN}
      - ./html:/var/www/html/${DOMAIN}
    ports:
      - "80:80"
    restart: always

  certbot:
    build: ./certbot
    env_file:
      - ./config.env
    volumes:
      - ./certbot_certs:/etc/letsencrypt
      - ./certbot_www:/var/www/certbot/${DOMAIN}
    depends_on:
      - nginx

  mellivora:
    image: mellivora
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOMAIN: ${DOMAIN}
    env_file:
      - ./config.env
    ports:
      - "443:443"
    volumes:
       - ./certbot_certs:/etc/nginx/ssl/
    #  - .:/var/www/mellivora
    #  - composerdependencies:/var/www/mellivora/include/thirdparty/composer
    links:
      - db
    depends_on: 
      - db
      - nginx
      - certbot

  db:
    image: mysql:5.6
    ports:
      - 13306:3306
    env_file:
      - ./config.env
    volumes:
      - dbdata:/var/lib/mysql
      - ./install/sql:/docker-entrypoint-initdb.d

  adminer:
      image: adminer
      restart: always
      ports:
        - 18080:8080
volumes:
  composerdependencies:
  dbdata:
